# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bmsm_A_cpp <- function(kbar, b, gamma_kbar, lamda, rho_m) {
    .Call('_MSM_Bmsm_A_cpp', PACKAGE = 'MSM', kbar, b, gamma_kbar, lamda, rho_m)
}

Bmsm_states_cpp <- function(m01, m02, kbar) {
    .Call('_MSM_Bmsm_states_cpp', PACKAGE = 'MSM', m01, m02, kbar)
}

Bmsm_filtered_cpp <- function(dat, A, gm, rhoe, sigma1, sigma2) {
    .Call('_MSM_Bmsm_filtered_cpp', PACKAGE = 'MSM', dat, A, gm, rhoe, sigma1, sigma2)
}

Bmsm_stage2_ll_cpp <- function(dat, A, gm, rhoe, sigma1, sigma2) {
    .Call('_MSM_Bmsm_stage2_ll_cpp', PACKAGE = 'MSM', dat, A, gm, rhoe, sigma1, sigma2)
}

Msm_A_cpp <- function(b, gamma_kbar, kbar) {
    .Call('_MSM_Msm_A_cpp', PACKAGE = 'MSM', b, gamma_kbar, kbar)
}

Msm_states_cpp <- function(m0, kbar) {
    .Call('_MSM_Msm_states_cpp', PACKAGE = 'MSM', m0, kbar)
}

Msm_likelihood_fast <- function(dat, sigma_gm, A) {
    .Call('_MSM_Msm_likelihood_fast', PACKAGE = 'MSM', dat, sigma_gm, A)
}

Msm_likelihood_cpp <- function(pimat0, omegat, A) {
    .Call('_MSM_Msm_likelihood_cpp', PACKAGE = 'MSM', pimat0, omegat, A)
}

Msm_ll_fast <- function(dat, sigma_gm, A) {
    .Call('_MSM_Msm_ll_fast', PACKAGE = 'MSM', dat, sigma_gm, A)
}

Msm_ll_cpp <- function(pimat0, omegat, A) {
    .Call('_MSM_Msm_ll_cpp', PACKAGE = 'MSM', pimat0, omegat, A)
}

Msm_smooth_cpp <- function(A, P) {
    .Call('_MSM_Msm_smooth_cpp', PACKAGE = 'MSM', A, P)
}

